spring:
  datasource:
    url: jdbc:sqlserver://172.27.192.163:1400;database=test_isolation
    username: sa
    password: 1234Hellowrold

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

logging:
  config: classpath:log4j2-test.xml
