spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_isolation
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  config: classpath:log4j2-test.xml
