spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  config: classpath:log4j2-test.xml
